Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(**check_kwargs)
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 492, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 89, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 531, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/diegomazuco/dev/orchestra/core/urls.py", line 22, in <module>
    path('', include('apps.dashboard.urls')),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/diegomazuco/dev/orchestra/apps/dashboard/urls.py", line 2, in <module>
    from . import views
  File "/home/diegomazuco/dev/orchestra/apps/dashboard/views.py", line 9, in <module>
    from apps.automacao_ipiranga.models import VeiculoIpiranga, CertificadoVeiculo
  File "/home/diegomazuco/dev/orchestra/apps/automacao_ipiranga/models.py", line 7, in <module>
    class VeiculoIpiranga(models.Model):
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 136, in __new__
    raise RuntimeError(
RuntimeError: Model class apps.automacao_ipiranga.models.VeiculoIpiranga doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
/home/diegomazuco/dev/orchestra/core/settings.py changed, reloading.
DEBUG: settings.py loaded
DEBUG: BASE_DIR defined
DEBUG: Security settings loaded
DEBUG: INSTALLED_APPS defined
DEBUG: MIDDLEWARE defined
DEBUG: TEMPLATES defined
DEBUG: WSGI_APPLICATION defined
DEBUG: DATABASES defined
DEBUG: AUTH_PASSWORD_VALIDATORS defined
DEBUG: Internationalization settings loaded
DEBUG: Static and Media files settings loaded
DEBUG: DEFAULT_AUTO_FIELD defined
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(**check_kwargs)
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 492, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/checks/registry.py", line 89, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 531, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/diegomazuco/dev/orchestra/core/urls.py", line 22, in <module>
    path('', include('apps.dashboard.urls')),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/diegomazuco/dev/orchestra/apps/dashboard/urls.py", line 2, in <module>
    from . import views
  File "/home/diegomazuco/dev/orchestra/apps/dashboard/views.py", line 9, in <module>
    from apps.automacao_ipiranga.models import VeiculoIpiranga, CertificadoVeiculo
  File "/home/diegomazuco/dev/orchestra/apps/automacao_ipiranga/models.py", line 7, in <module>
    class VeiculoIpiranga(models.Model):
  File "/home/diegomazuco/dev/orchestra/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 136, in __new__
    raise RuntimeError(
RuntimeError: Model class apps.automacao_ipiranga.models.VeiculoIpiranga doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
/home/diegomazuco/dev/orchestra/core/settings.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
DEBUG: settings.py loaded
DEBUG: BASE_DIR defined
DEBUG: Security settings loaded
DEBUG: INSTALLED_APPS defined
DEBUG: MIDDLEWARE defined
DEBUG: TEMPLATES defined
DEBUG: WSGI_APPLICATION defined
DEBUG: DATABASES defined
DEBUG: AUTH_PASSWORD_VALIDATORS defined
DEBUG: Internationalization settings loaded
DEBUG: Static and Media files settings loaded
DEBUG: DEFAULT_AUTO_FIELD defined
